### ISSUE TITLE
Using getImage() without getting a new challange

### ISSUE THREAD

**Issue by soul1229** [noahcoolboy/funcaptcha#50]
First of all, thank you so much for your work!

I'm fairly new to JS, so this question may be too easy to answer :)

This code works great:
```
const fun = require("funcaptcha")
const token = await fun.getToken({
    pkey: "<public_key>", // The public key
    site: "<site>" // The site which contains the funcaptcha
}).then(async token => {
    let session = new fun.Session(token);
    let challenge = await session.getChallenge();
    image = await challenge.getImage()
});
```

But I have a need to solve the "challenge" from the outside. For example, from a text document.  For this, I need to get images from my saved challenge using getImage() without creating a new challenge or session.

I tried the following code:

```
const fun = require('funcaptcha')
challenge = <my saved challange>
image = await challenge.getImage()
```

But I get TypeError: challenge.getImage is not a function

How can I solve this problem and which link can I use to buy you a cup of coffee? :)

**Comment by noahcoolboy** [comment]
Hi!

I'm not sure I'm able to follow what the problem is.
Do you need to create a copy of the challenge object?
If so, try copying the token instead, and fetching the challenge on your external server instead.
This will make it so you can fetch the token on one and solve it on another server.

I have a ko-fi page if you would like to support me!
https://ko-fi.com/noahcoolboy
